### ISSUE TITLE
重复code

### ISSUE THREAD

**Issue by answer33** [ybwdaisy/china-area-data#1]
710700 710701 安乐区
710700 710702 七堵区
710700 710703 信义区
710800 710701 东区
710800 710702 北区
710800 710703 香山区
存在重复code
-------------------
最后三个应该改为
710800 710801 东区
710800 710802 北区
710800 710803 香山区

**Comment by ybwdaisy** [comment]
> ## 710700 710701 安乐区
> 710700 710702 七堵区
> 710700 710703 信义区
> 710800 710701 东区
> 710800 710702 北区
> 710800 710703 香山区
> 存在重复code
> 最后三个应该改为 710800 710801 东区 710800 710802 北区 710800 710803 香山区

已更新：https://github.com/ybwdaisy/china-area-data/pull/2
